"""Regenerate public/js/lamp.js from public/img/logo.svg (one drawing, two uses).
The SVG ids/classes 'lmp2' become a per-instance id so several lamps can live on one page."""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
svg = (ROOT / 'public/img/logo.svg').read_text(encoding='utf-8')
m = re.search(r'  <style>\n(.*?)</style>\n', svg, re.S)
anim = m.group(1).replace('lmp2', '${id}').rstrip()
body = svg[:m.start()] + '  <style>${anim}</style>\n' + svg[m.end():]
body = body.replace('lmp2', '${id}')
body = body.replace('width="120" height="120" role="img" aria-label="Mishkat — light upon light (24:35)"',
                    'width="${size}" height="${size}" role="img" aria-label="${title}"')
anchor = '  <circle cx="75" cy="47" r="1.2" fill="#ffffff"/>\n'
assert anchor in body
body = body.replace(anchor, anchor + "  ${word ? `<text class=\"lamp-word\" x=\"60\" y=\"69\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-family=\"Amiri Quran, Amiri, serif\" font-size=\"15\" fill=\"#3b2400\"></text>` : ''}\n")
head = '''// «مثل نوره كمشكاة فيها مصباح، المصباح في زجاجة، الزجاجة كأنها كوكب دري، يوقد من شجرة
// مباركة زيتونة لا شرقية ولا غربية، يكاد زيتها يضيء ولو لم تمسسه نار، نور على نور» (24:35)
// Drawn after the tafsir of As-Sa'di (checked word by word on 5 Oct, author's remark: the glass and the «planet» were
// confused): «كمشكاة» أي: كوة … «فيها مصباح» … «الزجاجة» من صفائها وبهائها «كأنها كوكب دري» أي: مضيء إضاءة الدر
// … «يوقد» ذلك المصباح الذي في تلك الزجاجة الدرية «من شجرة مباركة زيتونة» … «نور على نور» أي: نور النار ونور الزيت.
//   المشكاة  = the niche that gathers the light — a mihrab arch;
//   المصباح = the lamp proper: a lit wick standing in the oil, INSIDE the glass;
//   الزجاجة = the clear glass vessel (a mosque lamp), which ITSELF shines like a pearl-white star (كوكب دري):
//              its own star rays and a pearl neon outline — there is no separate planet behind it;
//   الزيت    = the clear olive oil the lamp is kindled from;
//   الشجرة  = an olive sprig, centred «لا شرقية ولا غربية», a thread of oil rising from it to the lamp;
//   نور على نور = the light of the fire and the light of the oil: stacked halos, breathing slowly.
// GENERATED by tools/make_lamp.py from public/img/logo.svg — edit the SVG, then run the script.
// An optional word slot shows the word being recited inside the glass, auto-fitted.
let uid = 0;

export function lampSVG({ size = 120, word = false, animated = true, title = 'Mishkat' } = {}) {
  const id = 'lmp' + (++uid);
  const anim = animated ? `
''' + anim + '''` : '';
  return `''' + body.rstrip() + '''`;
}

// Put a word inside the glass, over the glowing oil; long words are compressed to fit, never cut.
const WORD_W = new Map();
export function setLampWord(svgRoot, word) {
  const t = svgRoot && svgRoot.querySelector('.lamp-word');
  if (!t) return;
  t.textContent = word || '';
  t.removeAttribute('textLength');
  t.removeAttribute('lengthAdjust');
  t.setAttribute('font-size', '15');
  if (!word) return;
  const maxW = 38; // the inside of the glass body
  try {
    // widths are remembered per word (measuring forces a layout of the SVG at every recited word)
    let w = WORD_W.get(word);
    if (w == null) { w = t.getComputedTextLength(); if (w > 0) { WORD_W.set(word, w); if (WORD_W.size > 3000) WORD_W.clear(); } }
    if (w > maxW) {
      const fs = Math.max(8, 15 * maxW / w);
      t.setAttribute('font-size', fs.toFixed(1));
      if (15 * maxW / w < 8) { t.setAttribute('textLength', maxW); t.setAttribute('lengthAdjust', 'spacingAndGlyphs'); }   // at the smallest size it still overflows
    }
  } catch (e) { t.setAttribute('textLength', maxW); t.setAttribute('lengthAdjust', 'spacingAndGlyphs'); }
}
'''
(ROOT / 'public/js/lamp.js').write_text(head, encoding='utf-8')
print('lamp.js regenerated')
