// (6 Oct 2026, T122) Vocabulary given to the speech-to-text engine (ElevenLabs Scribe «keyterms»): the 114 surah
// names taken from core.json (never typed by hand) + the words visitors say most in Mishkat (services, pillars,
// prophets, places). Measured on eval/stt: «الزكاة» heard «الذكاء», «Surah Al-Kahf» heard «Sarah Alcoff», «سورة»
// heard «صورة» without it; all three right with it.
//   node data_build/build_stt_terms.mjs   → functions/_lib/stt_terms.js
import { readFileSync, writeFileSync } from 'node:fs';

const core = JSON.parse(readFileSync(new URL('../public/data/core.json', import.meta.url), 'utf8'));
const AR_TERMS = `القرآن الكريم، سورة، آية، آيات، تفسير، جزء، حزب، مكية، مدنية، البسملة، آية الكرسي، المعوذتين، خواتيم البقرة،
الصلاة، الزكاة، الصيام، الحج، العمرة، الوضوء، التيمم، الطهارة، القبلة، الأذان، الإقامة، الجمعة، التراويح، الوتر، السجود، الخشوع،
التوحيد، الشرك، الإيمان، الإحسان، الإسلام، أركان الإسلام، أركان الإيمان، الصبر، التوبة، الاستغفار، الدعاء، الأذكار، الرقية، التسبيح،
بر الوالدين، صلة الرحم، الربا، الميراث، الطلاق، النكاح، الحجاب، الجهاد، الجنة، النار، القيامة، البعث، الصراط، الميزان، الشفاعة،
الملائكة، جبريل، إبليس، الشيطان، الجن، آدم، نوح، إبراهيم، إسماعيل، إسحاق، يعقوب، موسى، هارون، عيسى، داود، سليمان، أيوب، زكريا، يحيى،
إلياس، اليسع، ذو الكفل، لوط، شعيب، صالح، إدريس، ذو القرنين، أصحاب الكهف، فرعون، قارون، النبي محمد، الصحابة، أبو بكر الصديق،
عمر بن الخطاب، عثمان بن عفان، علي بن أبي طالب، خديجة، عائشة، الهجرة، غزوة بدر، غزوة أحد، الخندق، فتح مكة، مكة المكرمة، المدينة المنورة،
المسجد الأقصى، الكعبة، ليلة القدر، رمضان، يوم عرفة، عاشوراء، تجويد، ختمة، تلاوة، حفظ، تكرار، مواقيت الصلاة، المسجد، الحديث، السنة،
صحيح البخاري، صحيح مسلم، أسماء الله الحسنى، الصمد، الفتوى، حلال، حرام، مشكاة`;
const EN_TERMS = `Quran, Surah, Ayah, verse, tafsir, juz, hizb, Meccan, Medinan, Basmala, Ayat al-Kursi, salah, zakat, fasting, Ramadan, Hajj, Umrah,
wudu, qibla, adhan, Jumuah, tawhid, shirk, iman, ihsan, pillars of Islam, patience, repentance, dua, dhikr, Paradise, Hellfire, Day of Judgement,
angels, Jibreel, Iblis, Satan, jinn, Adam, Nuh, Ibrahim, Ismail, Ishaq, Yaqub, Musa, Harun, Isa, Maryam, Dawud, Sulayman, Yunus, Ayyub, Zakariya,
Yahya, Prophet Muhammad, Pharaoh, companions, hadith, Sunnah, Bukhari, Muslim, halal, haram, fatwa, khatma, tajweed, hifz, Mishkat`;
const clean = (s) => s.replace(/['’ʿ]/g, '').trim();
const split = (s, sep) => s.split(sep).map(x => clean(x.replace(/\s+/g, ' '))).filter(Boolean);
const ar = [...new Set([...core.suras.map(s => s.ar), ...split(AR_TERMS, /[،\n]/)])];
const en = [...new Set([...core.suras.map(s => clean(s.tr)), ...split(EN_TERMS, /[,\n]/)])];
const out = `// Generated by data_build/build_stt_terms.mjs from public/data/core.json (surah names) + Mishkat's vocabulary — do not edit.
export const STT_TERMS = ${JSON.stringify({ ar, en })};
`;
writeFileSync(new URL('../functions/_lib/stt_terms.js', import.meta.url), out);
console.log('ar', ar.length, 'en', en.length);
